package attacks.app.enumerations;

public enum Mitigations {
	Checking_headers_in_traffic,
	Ensure_that_the_content_of_the_file_doesnt_depend_solely_on_the_file_extension,
	Load_configuration_from_separate_process_and_memory_space,
	Implement_communications_to_and_from_the_registry_using_secure_protocols,
	Ensure_that_the_proper_permissions_are_set_on_local_files,
	Validate_software_updates_before_installing,
	Leverage_anti_virus_products,
	Include_hosts_file,
	Ensure_that_design_documentation_is_saved_in_a_secure_location,
	Identify_programs_that_may_be_used_to_acquire_process_information_and_block_them,
	Ensure_that_client_process_and_or_message_is_authenticated,
	Get_your_Public_Key_signed_by_a_Certificate_Authority,
	Ensure_users_are_not_reusing_username_password_combinations,
	Use_strong_session_identifiers,
	Users_should_not_open_other_tabs_in_the_browser,
	Always_invalidate_a_session_ID_after_the_user_logout,
	Use_session_identifiers_that_are_difficult_to_guess_or_brute_force,
	Ensure_the_web_server_implements_all_relevant_security_patches,
	Apply_the_least_privilege_principles,
	Limit_users_and_accounts_that_have_remote_interactive_login_access,
}