package attacks.app.enumerations;

public enum Prerequisites {
	The_target_host_is_logging_the_action_and_data_of_the_user,
	The_target_must_use_the_affected_file_without_verifying_its_integrity,
	Configuration_files_must_be_modifiable_by_the_attacker,
	A_SIM_card_that_relies_on_the_DES_cipher,
	Access_to_the_software_during_the_development_phase,
	Physical_access_to_the_system,
	Advanced_knowledge_about_the_target_system_and_sub_components,
	Access_to_the_component_currently_deployed_at_a_victim_location,
	The_adversary_requires_knowledge_of_and_access_to_network_route,
	An_attacker_and_the_victim_are_both_using_the_same_WiFi_network,
	HTTP_TRACE_is_enabled_on_the_web_server,
	Session_identifiers_that_remain_unchanged_when_the_privilege_levels_change,
	The_targeted_site_must_contain_hidden_fields_to_be_modified,
	Targeted_software_is_utilizing_application_framework_APIs,
	The_attacker_must_have_direct_access_to_the_target_server,
	Web_services_check_the_signature_of_the_API_calls,
	The_various_resources_must_be_discoverable_by_the_attacker,
	The_ability_to_calculate_a_card_checksum_and_write_out_a_valid_checksum_value,
	Requires_the_existence_of_a_physical_target,
	Application_is_connected_to_the_Windows_domain,
}